### ISSUE TITLE
Mihai Pop (maximisu90) review

### ISSUE THREAD

**Issue by maximisu90** [teokem/project-work-2021-si8881wo#2]
Documentation:

    title and abstract of the project (max 300 words)
**I would have liked a clearer abstract **
    includes instructions on how to run the notebook
**I was running the cells sequentially **
    includes the required packages in an environment.yml file
**yes**
    includes a brief explanation of the reason each package/library was used
**I cannot discern which package is used for which task as I am not familiar with julia**

    includes rich documentation using Markdown (equations, tables, links, images or videos)
**Yes**
    is reproducible, i.e., someone else should be able to redo the steps
**Yes**
Input/Output:

    uses pandas to read large data sets or numpy to load data from text files
**Yes**

    uses pandas to save to disk the processed or generated data
**yes**

Scientific computing/data processing:

    performs numerical operations (numpy, scipy, pandas) or manipulates, groups, and aggregates a data set (pandas)

Data visualization:

    includes at least one composite plot (inset or multiple panels)
**Yes, However the second plot in the evaluation notebook does not have labels for the different lines plotted**
    produces publication ready quality figures (see here for an editorial guide on Graphical Excellence):
        the figures are 89 mm wide (single column) or 183 mm wide (double column)
        the axes are labeled
        the font sizes are sufficiently large
        the figures are saved as rasterized images (300 dpi) or vector art
**Figures are saved the quality is good but the units are not explained ( Or I did not understand them).**

Version control, sharing, and archiving:

    is archived in a repository with a digital object identifier (DOI)
**Yes**

Free comments

What is T_{RL} (E)? what is E/Delta?

**Comment by si8881wo** [comment]
Thanks for the thorough review. I had a bit of trouble with the formatting of your issue but I think I was able to identify the things that needed to be addressed.

I changed the following things according to your comments:
* I included a sentence on running the notebook either sequentially or via 'Run->Run all cells' in the readme
* I added a few words in evaluation.ipynb where the contents of the csv files are explained to clear up what T_RL and E are. 

I chose not to change a few things you commented on for the following reasons:
* I don't know what part of the abstract is unclear. This is meant as supplement to a (not yet published) bigger work, that would put things into context. I think there is not really a way to solve this without an unreasonable amount of additional/double effort.
* The size of the saved plots doesn't play a big role since they can be saved as pdf where the line plots are saved as vectors, so they scale loss free. The heatmaps are saved with "native resolution" i.e. all the pixels the array provides. (the 'size=...' argument in the plot command in julia does afaik only influence the proportion of the figure that is saved, so it's kind of irrelevant)

Again thanks for the constructive feedback!
