### ISSUE TITLE
Peer-reveiws

### ISSUE THREAD

**Issue by exook** [teokem/project-work-2021-si8881wo#3]
This is a very well designed notebook. There is a very nice balance between explaining the physics and explaining the code. The text cells are concise and to the point, and the code cells are well documented and can be understood independently form the text. Though a written summary for some code cells would have been nice. The notebook is also an exceptional showcase example for the benefits of using Julia in physics, a language which I had never seen before.

Below are some bullet points of improvements I would suggest

# From checklist
- [ ] title and abstract of the project (max 300 words)
 - There is a nice physics introduction, but I think a short abstract would be a nice way to prepare the reader of what will be done in the notebook as a whole, and maybe how the two notebooks are related
- [ ] Data visualization:
 - [ ] the figures are 89 mm wide (single column) or 183 mm wide (double column)
  - I cannot verify the dimensions of the plots in the code
 - [ ] the axes are labeled
  - Coming from a different field, units would have been nice on the axes labels

# fbs.ipynb

## General
* I would connect the text to the cell below a bit more. Maybe write some descriptive text above each code cell to explain what will be done, especially since some of the audience might not be used to Julia. For cell 11 I think it is an interactive slider, but since the WebIO doesn’t work in binder I can't be sure. This could have been described in a text cell above
* Add a simple text note to assure the user that the error messages regarding WebIO will not affect the results/experience
* Coming From a different field I would have liked a small description of what what “band structure” is, maybe a figure form Wikipedia.

## Typos
* Cell 7. Paragraph 2. 
* Sentence 2. “there” -> “three”
* Sentence 3. “We have build” -> “We have built”
* Cell 8. “Neglecting the potential V….” very long sentence
* Cell 10. Paragraph 2. Sentence 1. “intitive” -> “intuitive”
* “I almost” -> “is almost”
* “Plot the hearmap” - > “plot the heatmap”
* “spectral function here (integrate over 𝑘) er eill”
* “Whil it is fulfilled” -> “while it is fulfilled”

# evaluation.ipynb
## General:
* It is difficult to understand how the two notebooks are related. Is fbs.ipnb responsible for the “simulations for the two-dimensional Topological insulator with impurities”? How are the two notebooks related

Typos:
* There are some more typos and grammar mistakes. If the notebooks will be shared with colleagues I would suggest to copy paste each text cell from both notebooks individually into a spellchecker

**Comment by si8881wo** [comment]
Thanks for the thorough review. Nice to hear that the project seems to be a good showcase for julia.

I changed the following things according to your comments:
* General: typos in various places
* fbs.ipynb:
  * added a non-interactive version of the plot where the user can still try out different parameters by changing the code cell in case WebIO doesn't work
  * added a note that there is no problem if the interactive plot doesn't work

I chose not to change a few things you commented on for the following reasons:
* Title, Abstract, relation of the notebooks: the introduction in the readme already states that fbs.ipynb is used to find a parameter for a more advanced simulation and evaluation.ipynb is used to evaluate output from that advanced simulation.
* dimension of the plots: since there is always the option to save the plots as pdf i.e. in a vector format the resolution will not be a problem (the heatmaps will be embedded with the "resolution" of the data array)
* The energy scales here are very small and as a matter of fact they are here usually scaled in terms of other quantities, for more details see [this paper](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.98.165423)

Again thanks for the constructive feedback!
